# Generated by Django 6.0.1 on 2026-01-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_wordlist_vocabulary_is_known_vocabulary_word_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
