# Generated by Django 6.0.1 on 2026-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_vocabulary_last_reviewed_vocabulary_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='words_processed',
            field=models.IntegerField(default=0),
        ),
    ]
