# Generated by Django 6.0.1 on 2026-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_wordlist_error_message_wordlist_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
