# Generated by Django 6.0.1 on 2026-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_vocabulary_audio_url_vocabulary_easiness_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
