# Generated by Django 4.2 on 2026-09-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0006_drop_global_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordlist",
            name="description",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddField(
            model_name="wordlist",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
