# Generated by Django 4.2 on 2026-09-12 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocab", "0007_wordlist_description_wordlist_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="audio_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="example_sentence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wordlist",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wordlist",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wordlist",
            name="total_words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wordlist",
            name="words_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="easiness_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="next_review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wordprogress",
            name="repetition_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
